[package]
name = "ferrumc"
version = "0.1.0"
edition = "2021"

# Compile all dependancies with the highest optimisation level
# This will make the first compile longer but will make builds faster
[profile.dev.package."*"]
opt-level = 3
[profile.release]
lto = true
[profile.dev]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.31.0", features = ["full"] }
byteorder = "1.4.3"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
anyhow = "1.0.72"
async-trait = "0.1.73"
once_cell = "1.18.0"
lazy_static = "1.4.0"

flate2 = "1.0"
fastnbt = "2.4.4"
fastanvil = "0.29.0"

[dependencies.uuid]
version = "1.4.1"
features = ["v3", "v4", "v5"]