[package]
name = "ferrumc"
version = "0.1.0"
edition = "2021"

# Compile all dependancies with the highest optimisation level
# This will make the first compile longer but will make builds faster
[profile.dev.package."*"]
opt-level = 3
[profile.release]
lto = true
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
byteorder = "1.4.3"
serde = { version = "1.0.188", features = ["derive", "alloc"] }
serde_json = "1.0.107"
anyhow = "1.0.75"
async-trait = "0.1.73"
once_cell = "1.18.0"
lazy_static = "1.4.0"
uuid = { version = "1.4.1", features = ["v4", "v3", "v5"] }
ferrumc_world = { path = "crates/ferrumc_world" }
serde_path_to_error = "0.1.14"
figlet-rs = "0.1.5"
owo-colors = "3.5.0"
log = "0.4.20"
pretty_env_logger = "0.5.0"
ferrumc_net = { path = "crates/ferrumc_net" }